### ISSUE TITLE
OptiPlex 3050

### ISSUE THREAD

**Issue by MastaChu** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#1]
Hi, I have tested your EFI on Catalina, Monterey, and Ventura... only Monterey runs but fails to install the latest 12 minutes... Can you share /explain how you made the installation? Your EFI should run on Monterey too, right?
thank you in advance!

**Comment by mavethee** [comment]
Yes, it should but it was made in mind of Ventura. 

I followed Dortania's OC Guide:
https://dortania.github.io/OpenCore-Install-Guide/

If you have any issues with Monterey, I assume its specific machine issue _(or skill issue)_, check:

1. BIOS settings, make sure to be up to date with Firmware and all the drivers,
2. Dump own ACPI files using SSDTTime,
3. Check troubleshooting, maybe your issue is there.

**Comment by MastaChu** [comment]
[Uploading opencore-2022-09-16-193050.txt…]()
Thank you for answering, i have now used Ventura, here is OpenCore log, can you take a look?

**Comment by MastaChu** [comment]
Hi, just letting you know that I have successfully made installation and finalization using your EFI...
Install was started with Olarila EFI, your EFI has been used after installation... Working very well... 
Thanks for sharing!

**Comment by mavethee** [comment]
Oralia 🤦🏻
