### ISSUE TITLE
What should I change for i5-6500?

### ISSUE THREAD

**Issue by turbozapekanka** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#3]
I have Dell 3050 MT model with i5-6500 cpu
Also plan to use AMD RX560 gpu and NVMe ssd

**Comment by mavethee** [comment]
I advise start from scratch, at least you would get a better understanding of whole process

https://dortania.github.io/OpenCore-Install-Guide/ <- Main guide.

But if you want, you can modify this EFI and be fine mostly.

1. /EFI/OC/ACPI - Dump your own DSDT and SSDTs using your DSDT for your machine (needed for everyone actually, since same model, same specs =/= same machine),

2. /EFI/OC/Kexts - Add NVMeFIx, remove USBInjectAll and follow this guide to map your USB, using USBInjectAll is not reccomended, but "somewhat" works, I don't have access to school's PC to map it properly:

https://github.com/USBToolBox/tool

3. /EFI/OC/config.plist: 

- Reconfigure config.plist using setup for Skylake
(https://dortania.github.io/OpenCore-Install-Guide/config.plist/skylake.html) 

a) Skip PlatformInfo, for Ventura you need KBL SMBIOS, if you don't wanna mess with RestrictEvents,
b) Remove children assigned to iGPU's PciRoot in DeviceProperties, and this child from guide to disable GPUs (do not change PciRoot, you dont wanna disable AMD):

https://dortania.github.io/OpenCore-Install-Guide/extras/spoof.html#deviceproperties-method,

c) clean out boot-args in NVRAM.

Should be everything I guess.

**Comment by mavethee** [comment]
Closing as if there's no other questions.
