### ISSUE TITLE
HDMI not work, screen black or purple

### ISSUE THREAD

**Issue by Epikaigle** [mavethee/Hackintosh-OpenCore-EFI-DELL-Optiplex-3050#4]
Hello, thanks for your sharing, but only my Displayport works. My hdmi port doesn't want to work. I have tried severals solutions but none of them worked.
I would like to know, if you have solved this problem ?
Thanks again for your work !

**Comment by mavethee** [comment]
I assume it requires deeper dive into Intel iGPU patching (especially connector types), my school uses DPs as primary source so I was focusing on DP only. Don't have access to machines anymore so yeah, follow this part:

https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html

**Comment by epikaigle444** [comment]
okay, I'll try that.

**Comment by epikaigle444** [comment]
What did you put as an option so that the port type is always set as DP (00040000) even when I try to set it to hdmi? for the 3 framebuffers.

![Capture d’écran 2023-01-29 à 19 07 56](https://user-images.githubusercontent.com/61425652/215347012-54544ad7-b086-41d7-8cda-e05d9895a087.png)
![Capture d’écran 2023-01-29 à 19 08 09](https://user-images.githubusercontent.com/61425652/215347017-f0b6f6d8-013a-4d53-b67e-11e53e542c8c.png)
![Capture d’écran 2023-01-29 à 19 08 21](https://user-images.githubusercontent.com/61425652/215347022-9c1fecca-5cd5-42f3-af5e-230ada05c191.png)

**Comment by epikaigle444** [comment]
The tutorial doesn't work with your EFI. Do you have an idea to solve this?
![Capture d’écran 2023-01-29 à 19 19 17](https://user-images.githubusercontent.com/61425652/215347513-7e3dd846-a158-429b-8efc-93bdf481f51d.png)
